CREATE DATABASE `fruit_trace`;

USE `fruit_trace`;

CREATE TABLE `t_anomalia` (
  `iID_ENTREGA` int(11) NOT NULL,
  `iID_USUARIO` int(11) NOT NULL,
  `iID_USUARIO2` int(11) NOT NULL,
  `dtFECHA` datetime NOT NULL,
  `sID_ETIQUETA` varchar(100) NOT NULL,
  `iID_AREA` int(11) NOT NULL,
  `iID_CINTA` int(11) NOT NULL,
  `dLATITUD` double(11,8) NOT NULL,
  `dLONGITUD` double(11,8) NOT NULL,
  `dPESO` double(11,5) NOT NULL,
  `sID_EQUIPO` varchar(100) NOT NULL,
  `sOBS` text NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_ENTREGA`,`sID_ETIQUETA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `t_area` (
  `iID_AREA` int(11) NOT NULL AUTO_INCREMENT,
  `sDESCRIPCION` varchar(250) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_AREA`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_cintas` (
  `iID_CINTA` int(11) NOT NULL AUTO_INCREMENT,
  `sCOLOR` varchar(250) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_CINTA`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_cosecha` (
  `iID_ENTREGA` int(11) NOT NULL,
  `iID_USUARIO` int(11) NOT NULL,
  `iID_USUARIO2` int(11) NOT NULL,
  `dtFECHA` int(11) NOT NULL,
  `sID_ETIQUETA` varchar(100) NOT NULL,
  `iID_AREA` int(11) NOT NULL,
  `iID_CINTA` int(11) NOT NULL,
  `dLATITUD` double(11,8) NOT NULL,
  `dLONGITUD` double(11,8) NOT NULL,
  `dPESO` double(11,5) NOT NULL,
  `sID_EQUIPO` varchar(100) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_ENTREGA`,`sID_ETIQUETA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_embolse` (
  `iID_ENTREGA` int(11) NOT NULL,
  `iID_USUARIO` int(11) NOT NULL,
  `iID_USUARIO2` int(11) NOT NULL,
  `dtFECHA` datetime NOT NULL,
  `sID_ETIQUETA` varchar(100) NOT NULL,
  `iID_AREA` int(11) NOT NULL,
  `iID_CINTA` int(11) NOT NULL,
  `dLATITUD` double(11,8) NOT NULL,
  `dLONGITUD` double(11,8) NOT NULL,
  `dPESO` double(11,5) NOT NULL,
  `sID_EQUIPO` varchar(100) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_ENTREGA`,`sID_ETIQUETA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_embolse_temp` (
  `iID_EMBOLSE` int(11) NOT NULL AUTO_INCREMENT,
  `iID_USUARIO` int(11) NOT NULL,
  `dtFECHA` datetime NOT NULL,
  `sID_ETIQUETA` varchar(100) NOT NULL,
  `dLATITUD` double(11,8) NOT NULL,
  `dLONGITUD` double(11,8) NOT NULL,
  `sID_EQUIPO` varchar(100) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_EMBOLSE`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_entrega` (
  `iID_ENTREGA` int(11) NOT NULL AUTO_INCREMENT,
  `iID_USUARIO` int(11) NOT NULL,
  `iID_USUARIO2` int(11) NOT NULL,
  `sID_ETIQUETA` varchar(100) NOT NULL,
  `iID_AREA` int(11) NOT NULL,
  `iID_CINTA` int(11) NOT NULL,
  `dtFECHA` datetime NOT NULL,
  `sID_ESTADO` varchar(100) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_ENTREGA`,`sID_ETIQUETA`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_equipos` (
  `sID_EQUIPO` varchar(100) NOT NULL,
  `sSERIE` varchar(11) NOT NULL,
  `sNOMBRE` varchar(250) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`sID_EQUIPO`,`sSERIE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_estados` (
  `iID_ESTADO` int(11) NOT NULL AUTO_INCREMENT,
  `sDESCRIPCION` varchar(250) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_ESTADO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_evaluacion` (
  `iID_EVALUACION` int(11) NOT NULL AUTO_INCREMENT,
  `ID_ENTREGA` int(11) NOT NULL,
  `iID_USUARIO` int(11) NOT NULL,
  `sID_ETIQUETA` int(11) NOT NULL,
  `dtFECHA` datetime NOT NULL,
  `iID_DATO` int(11) NOT NULL,
  `sOBS` text NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_EVALUACION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `t_inventario` (
  `sID_ETIQUETA` varchar(100) NOT NULL,
  `iID_ESTADO` int(11) NOT NULL,
  `iID_AREA` int(11) NOT NULL,
  `dtFECHA1` date NOT NULL,
  `dtFECHA2` date NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`sID_ETIQUETA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_pos` (
  `iPOSID` int(11) NOT NULL AUTO_INCREMENT,
  `iID_AREA` int(11) NOT NULL,
  `dLATITUD` double(11,10) NOT NULL,
  `dLONGITUD` double(11,10) NOT NULL,
  `iPOS` int(11) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  UNIQUE KEY `iPOSID` (`iPOSID`),
  KEY `iId_area_dLatitud_dlongitud` (`iID_AREA`,`dLATITUD`,`dLONGITUD`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_propiedaevalua` (
  `iID_DATO` int(11) NOT NULL AUTO_INCREMENT,
  `sDESCRIPCION_DATO` varchar(250) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_DATO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_roles` (
  `iID_ROL` int(11) NOT NULL AUTO_INCREMENT,
  `sDESCRIPCION` varchar(250) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE `t_usuarios` (
  `iID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `sNOMBRE` varchar(250) NOT NULL,
  `sAPELLIDO1` varchar(250) NOT NULL,
  `sAPELLIDO2` varchar(250) NOT NULL,
  `sCEDULA` int(11) NOT NULL,
  `iID_ROL` int(11) NOT NULL,
  `bACTIVO` tinyint(1) NOT NULL,
  PRIMARY KEY (`iID_USUARIO`),
  UNIQUE KEY `iId_usuario_sCedula` (`iID_USUARIO`,`sCEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

